package com.teststellar;

public class AccountStore {

    public static final String GOD_PUBLIC_KEY = "GBW74UVOXKGHO3WX6AV5ZGTB4JYBKCEJOUQAUSI25NRO3PKY5BC7WYZS";
    public static final String GOD_SECRET_KEY = "SA3W53XXG64ITFFIYQSBIJDG26LMXYRIMEVMNQMFAQJOYCZACCYBA34L";

    public static final String SOURCE_PUBLIC_KEY ="GCY2M7ALDMT5LO7L5OLRIL22PJVUCSQQ54YVYGVRRFG3Z5ZRLI6RLTSU";
    public static final String SOURCE_PRIVATE_KEY ="SBYL5BRKUJQIVT7V3TTUGEFVHNSJTK7EUFUUUNTWGCTCLTFYAGFV5PJ4";

    public static final String DESTINATION_PUBLIC_KEY ="GAGTISY75DSRTI2GJ5RUUTGHPKLDOHOFXD4SWYV7YVM4BHJQ5COZI4YX";
    public static final String DESTINATION_PRIVATE_KEY ="SBCPS4VSJYKL3OCX356RNKHBK7EQFUKBF7LF45ARZUZIDW7TRFLSC4YD";

    public static final String ISSUER_PUBLIC_KEY =  "GA6P7AF7MVC4FCLRCBUCNMQ4J67W3RCMMHSFJFHYBWK2EG3ITMY6C33Q";
    public static final String ISSUER_PRIVATE_KEY = "SBNTTARCY6YPCB6LHYHAAFXDZPXEQJCRPM7F6MWXNZWTAVEIU7H5B4UW";
}
